GET http://127.0.0.1:4567/api/v1/players HTTP/1.1

###

GET http://127.0.0.1:4567/api/v1/players/1 HTTP/1.1

###
POST http://127.0.0.1:4567/api/v1/players HTTP/1.1
content-type: application/json

{
    "first_name": "heitor",
    "last_name": "last",
    "username": "lucass",
    "password": "senha",
    "email": "a@b.caaa"
}

###

PUT http://127.0.0.1:4567/api/v1/players/1 HTTP/1.1
content-type: application/json

{
    "first_name": "first alterado",
    "last_name": "last alterado",
    "username": "usuarioAlterado",
    "password": "senhaAlterada",
    "email": "c@b.a"
}

###

PATCH http://127.0.0.1:4567/api/v1/players/1 HTTP/1.1
content-type: application/json

{
    "first_name": "first alterado"
}

###

DELETE http://127.0.0.1:4567/api/v1/players/1 HTTP/1.1