CREATE TABLE IF NOT EXISTS "PLAYER" (
    "PLAYER_ID" SERIAL PRIMARY KEY,
    "FIRST_NAME" VARCHAR(50) NOT NULL,
    "LAST_NAME" VARCHAR(50) NOT NULL,
    "USERNAME" VARCHAR(50) UNIQUE NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "EMAIL" VARCHAR(100) UNIQUE NOT NULL,
    "REGISTRATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "MATCH" (
    "MATCH_ID" SERIAL PRIMARY KEY,
    "PLAYER_1_ID" INT NOT NULL,
    "PLAYER_2_ID" INT NOT NULL,
    "IS_DRAW" BOOLEAN DEFAULT FALSE,
    "GAME_MODE" VARCHAR(50) NOT NULL,
    "WINNER_ID" INT NULL,
    "START_DATETIME" TIMESTAMP NOT NULL,
    "END_DATETIME" TIMESTAMP NULL,
    CONSTRAINT "CHK_DIFFERENT_PLAYERS" CHECK ("PLAYER_1_ID" <> "PLAYER_2_ID"),
    CONSTRAINT "FK_MATCH_PLAYER1" FOREIGN KEY ("PLAYER_1_ID") REFERENCES "PLAYER"("PLAYER_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_MATCH_PLAYER2" FOREIGN KEY ("PLAYER_2_ID") REFERENCES "PLAYER"("PLAYER_ID") ON DELETE CASCADE,
    CONSTRAINT "FK_MATCH_WINNER" FOREIGN KEY ("WINNER_ID") REFERENCES "PLAYER"("PLAYER_ID") ON DELETE SET NULL
);
